"""Add ai_description and instagram_audio_url to videos

Revision ID: e59a9c071a8e
Revises: bd94eb97bd7f
Create Date: 2025-08-22 20:11:47.326272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59a9c071a8e'
down_revision = 'bd94eb97bd7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('ai_description', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('instagram_audio_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'instagram_audio_url')
    op.drop_column('videos', 'ai_description')
    # ### end Alembic commands ###