[phases.setup]
nixPkgs = ["python311", "ffmpeg", "pkg-config", "gcc", "python311Packages.pip"]

[phases.install]
cmds = ["cd apps/backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "cd apps/backend && gunicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 300"